---
organization: cloudnativerioja
teams:
  - name: Collaborators
    description: Members of Cloud Native Rioja
    privacy: closed
    members:
      - username: user2
        role: member
  - name: myteam2
    description: team 2 description
    privacy: secret
    members:
      - username: user1
        role: maintainer
