---
######################
# Organization
######################

organization: cloudnativerioja
teams:
  - name: Collaborators
    description: Members of Cloud Native Rioja
    privacy: closed
    members:
      - username: gbalcony
        role: member
      - username: farconada
        role: member
      - username: borjareinares
        role: member
      - username: chuchip
        role: member
      - username: pabpereza
        role: member
      - username: darues
        role: member
      - username: jorgelon
        role: member
      - username: EnriqueHormilla
        role: member
      - username: Aberasturi
        role: member
      - username: edumgui
        role: member
  - name: Organizers
    description: Organizers of Cloud Native Rioja
    privacy: secret
    members:
      - username: dcristobalhMad
        role: maintainer
      - username: statickidz
        role: member
      - username: mario-ezquerro
        role: member

######################
# Repositories
######################

repositories:
  - name: github-org-iac
    description: "Repository to manage users and teams in the github organisation with pulumi"
    visibility: public
    topics: [iac, pulumi, github, golang, organization, cloudnativerioja]
  - name: cloudflare-iac-rioja
    description: "Repository to manage cloudnativerioja.com DNS with pulumi and Golang"
    visibility: public
    #topics: [iac, pulumi, cloudflare, golang, DNS, cloudnativerioja] # Not supported yet
  - name: cluster-demos
    description: "Repository to manage CIVO cluster demos with pulumi and Golang"
    visibility: public
    #topics: [iac, pulumi, golang, kubernetes, cluster, cloudnativerioja]
